# Generated by Django 3.2.5 on 2021-07-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210721_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb_link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
    ]
