# Generated by Django 3.2.5 on 2021-07-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'upVote'), (2, 'follow'), (3, 'post'), (4, 'answer'), (5, 'comment')], default=0),
        ),
    ]
